### ISSUE TITLE
Lien musique non fonctionnel

### ISSUE THREAD

**Issue by mchaaar** [WildCodeSchool/bordeaux-p2-202109-wildplaylist#61]
Quand je suis connecté et que je vais sur un profil qui n'est pas le mien, si je clique sur le lien d'une musique que l'utilisateur a posté je suis redirigé vers un 404.

**Comment by mchaaar** [comment]
*edit même problème si c'est mon profil

**Comment by afeynaud** [comment]
Thanks Mathis for your feedback. Our great dev Xavier resolved this issue.
